# 1. Imagem base oficial do Spark já utilizada
FROM apache/spark:3.5.7-java17-python3

# 2. Usuário 'root' para poder instalar pacotes
USER root

# 3. Instala a biblioteca na imagem
RUN pip install psycopg2-binary